### ISSUE TITLE
[UPDATE] user API 클라이언트와의 테스트를 통한 로직 및 버그 수정

### ISSUE THREAD

**Issue by soon327** [codestates/yourcat-server#19]
### ISSUE
- Group:   `server`
- Type: 'update'
- Detail: user API 로직 및 버그 수정

### TODO
1. [ ] 회원가입,로그인 로직 테스트 후 수정
2. [ ] RefreshToken 처리 해결
3. [ ] 소셜로그인 기능 구현
